### ISSUE TITLE
Flood protection triggers on the when sending to sp.php

### ISSUE THREAD

**Issue by OPROSVOs** [iBoonie/namesyncredux#1]
It is probably because the browser sends first an HTTP OPTIONS to the server and then after it verified the CORS, it sends the actual HTTP POST. Maybe that causes a problem with the flood protect.
Here are the connections with the HTTP 429 error response:
![image](https://user-images.githubusercontent.com/19379091/148704267-a789e3de-2448-4584-8042-2e1c3bfa1a55.png)
One solution would be to only count HTTP POST or HTTP GET for the flood protection or double all values / have even values.

Edit: It still answers HTTP 429 after replying a second time 30 seconds after the first post.

**Comment by iBoonie** [comment]
Ive pushed a fix for this, and increased the default settings. These can be tweaked later if need be.

**Comment by OPROSVOs** [comment]
![image](https://user-images.githubusercontent.com/19379091/148707296-c5243912-c424-4fbe-acf2-6456ccdb6ad0.png)
There is still something not right. It either triggers on normal use or doesn't reset.
Try testing the flood protection on its own.

**Comment by iBoonie** [comment]
Yup, you are correct, reopening. Ill have to look into this tomorrow. I may just swap to what you are using for flood protection since its tested. Mine was working locally, but its dumping garbage data on my host.

**Comment by OPROSVOs** [comment]
Thanks.
I just used [this](https://github.com/frdl/php-floodprotection) one and verified that it saved a file to a /tmp path on an tmpfs and tested the triggering.  
And i had that after the CORS header / exiting when its an options request so it doesn't add up twice.

**Comment by iBoonie** [comment]
This *should* be good now. I'll leave this open for a while just in case it isn't.

**Comment by OPROSVOs** [comment]
Tested it a few times and it worked. Should be fixed then.

**Comment by OPROSVOs** [comment]
I was too early: After posting to a new thread it triggered it again.
![grafik](https://user-images.githubusercontent.com/19379091/149645818-0ec34303-2d2f-486d-b1cf-bb2cc8739be0.png)

**Comment by iBoonie** [comment]
Woops, I was writing flood for submitting and quoting to the same file, so if one would try and grab a post multiple times, it would blast past the flood check for submitting too.
