### ISSUE TITLE
secure trip salt

### ISSUE THREAD

**Issue by OPROSVOs** [iBoonie/namesyncredux#2]
Can we agree on a secure trip salt across all servers so the secure trip is the same?
Right now syncing from multible servers results in two different trips.
I tried the salt in the config but you changed this.

Putting it into github defeats its purpose. Can you send the salt here so i can set this up?
https://m8q16hakamiuv8ch.myfritz.net/namesync/securetripsalt.php?salt=
Later on i restrict access to this or delete this script.

**Comment by iBoonie** [comment]
Done.

**Comment by OPROSVOs** [comment]
Can you repeat it once, i had a typo.

**Comment by iBoonie** [comment]
It had & in it which got stripped out. Ive just shortened to to what you have now and updates it on my side.

**Comment by OPROSVOs** [comment]
Yes, everything in quotation made it. 
I updated it, tested it, both return the same. Thanks.
