### ISSUE TITLE
Empty name not allowed and the catalog view is not working right

### ISSUE THREAD

**Issue by OPROSVOs** [iBoonie/namesyncredux#4]
## Empty names
Leaving the name all empty and just using the subject causes the server to not accept the post with the error "invalid name".
Instead of checking for `is_null($name)`, checking for `is_null($name)&&is_null($email)&&is_null($subject)` in sp.php line 26 would fix this.

## Catalog sync
And for the catalog sync to work, the thread parameter in qp.php has multible threads comma separated like `https://nsredux.com/namesync/qp.php?b=b&t=878719219,878729635,878731553,878731419,878731460`
which causes an Error 406.
You could allow a ` , ` additionally to any number and check when its present. Then have a different query that is ` OR `ed together.
But thats a bit more work.

## Minor things
One could flag an anon post later on with some name and troll by giving every anon a name.
The server side could deliver the timestamp of the post so the client could verify this with the thread data. If its within a few seconds, all is fine. With a timestamp this could be done on the client side but this inflates the data a bit.

Another thing would be to check the `Origin` header from the browser to be `https://boards.4chan.org/` in sp.php
And the `X-Requested-With` header to have NameSync at position 0 present in sp.php to make sure its from the extension.

**Comment by iBoonie** [comment]
Fixed empty names, added some checks for `Origin` and `X-Requested-With` headers. I already have [checks in place](https://github.com/iBoonie/namesyncredux/blob/main/require/CRON_UPDATE_BOARD_DATA.php) from before to combat name trolling. I parse the 4chan board API and keep track of previous posts, if your post # is behind the one I already have logged, it will fail. If you mean for posts that have yet to be made, they would have to guess the post number (and hope its in the same thread), and they only get 4 posts a minute to try before getting limited.

Catalog sync should really be its own file, it shouldn't be mashed into qp.php (unless stock namesync does this, but I think it's new to frensync).

**Comment by OPROSVOs** [comment]
Perfect. Thats done then.
Having a post behind another is still possible if one has a slow network and theres a high activity. There have been atleast two posts in the same milisecond as well and some clients have a clock offset of some seconds. Thats why i'm a bit careful locking that down without throughly testing it. 
I ment that a troll could have a script running that checks every few seconds for a new post and instantly flags this with a name.
But thats details for when it gets larger.

Catalog sync is still stock NS code and done in the same file because the query doesn't differentiate on which page it syncs.
![image](https://user-images.githubusercontent.com/19379091/170060182-55ed3390-a8a8-4411-b5b0-c745be7d3a7f.png)

For example in a paged view there could be 10 different threads with 3 posts each being shown - each could have a name.
The catalog query just has all threads from all pages with just the first post being interesting.
Or if Appchan is fancy, you could have weird things like two open threads at the same time on one page.

For compatibility having it in qp.php would be great but i agree. It depends how you set it up - like RISC or CISC have one query functon per file or one file for all queries.
Maybe an cq.php with the board, thread numbers and the limit of 1 or 3 posts per thread would be more elegant but that breaks compatibility for now. Let me test first whether that can be split up easily in the client or whether that breaks things.

But also having a single post in a thread on a board as a query would be nice. There is that ancient bug where 4chanX loads in a quoted post from another thread and the name for that one is not synced. And thats also a bit difficult on the client side if theres no distinct event for loading that external post.

EDIT: Having simple queries also makes caching easier. I've added a cache to it and it has like >90% hit rate where the server just repeats the last result to the next person. That greatly reduced the database load to a single write and read per new post / update.

**Comment by OPROSVOs** [comment]
![image](https://user-images.githubusercontent.com/19379091/170666209-733a79c0-bae7-4c68-a204-870155ab641b.png)
I'm getting HTTP 405 again on the options request. The data itself is correct if you ignore CORS.
Seeing that you added a $ recently, there might be some bug present.

Edit: Now its a 1 being returned, which errors out in the json parse.

**Comment by iBoonie** [comment]
Yep, that would be because I didn't test before pushing (bad me, bad). Ill work on catalog syncing when i'm not to busy.
For caching, honestly all of this could just be converted to a flat-file DB, it would be extremely cache friendly and fast.

**Comment by OPROSVOs** [comment]
I also did that for simple things. A bit down time is not too bad since its all redundant. 
Thanks for working on it in the first place.

If you want to test this, change line 137 in frensync to `var onload_proxy =function(t){console.log(this,t);return this.status&&(t=this),t.target?onload(t.target):((null!=onload)?onload(t):false)};` and you get the result dumped in the catalog for all three servers. And have the GM_API XHR unchecked in the options if you want to use the networking tab.

I als need to work on it a bit but my approach was to let the database deal with it and have a large query with all ids:
`SELECT distinct(thread) FROM sync where FIND_IN_SET(thread,{$t}) and board={$b};` where $t = "1,2,3" and $b ="b";

**Comment by iBoonie** [comment]
Had an hour, catalog query is in and tested.
